### ISSUE TITLE
Comparing PINT and tempo: periodicity in (PINT-tempo) residuals

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#301] opened 2017-04-11 18:49 UTC
David Nice and I are working on comparing tempo and PINT by looking at parameter values and timing residuals for the NANOGrav 11-year dataset.  Before doing the comparison, we removed all noise parameters and re-fit in tempo.  We then read the tempo parfile into PINT, ran the fit in PINT, and compared the pre- and post-fit parameter values and residuals.

For most pulsars, the parameter values are well within the 1-sigma pre-fit parameter error bars.  In some, like J2145-0750, there is a periodic difference in DMX parameters.  So although the parameter differences are well within the error bar, there is something systematic going on.  Also, a number of pulsars show a ~1-yr periodicity when we subtract the pre-fit from post-fit residuals.  The amplitude of the difference is frequency-dependent.

I'm attaching a few plots to illustrate this.  For the plots attached, the differences in astrometric and spin parameters (ELAT, ELONG, F0, F1, PX, PMELONG, PMELAT) between tempo and PINT are generally larger than differences in other parameters, with some exceptions.

We're trying to sort out the origin of this periodicity.  Some ideas/questions:
- Does PINT use any sort of solar wind model?
- In what reference frame does PINT calculate DMX?  Does it account for the Earth's motion (because the observed radio frequency will be Doppler-shifted)?  My understanding is that tempo does account for this.  The magnitude of the difference in residuals is consistent with that expected from this effect.

Have these parameter and residual differences been seen before?  Maybe someone on the PINT team is already aware of this and knows the origin.

To accompany the plot legends:
- The residual plots show (postfit resids - prefit resids), with frequency bands color-coded as in the legend.  For long datasets, the periodic nature becomes more apparent with GUPPI/PUPPI, so we include plots that zoom in on those epochs.
- For the parameter comparison plots: (1) Blue stars show the absolute value of the PINT-fitted parameter value subtracted from the tempo-fitted parameter value, divided by the tempo-fitted parameter value's 1-sigma error bar.  (2) We ran 10 iterations of tempo for isolated MSPs, and 50 iterations for binary MSPs.  Orange x's show the same as the blue stars, but compared to the multiple-iteration tempo-fitted values rather than single-iteration.  (3)  The green crosses show the same comparison for parameter values from tempo vs. values from multiple-iteration tempo runs.  We did this to check if differences between PINT and tempo are affected by tempo having been run for too few iterations, and find that this is not the case.

[tempovspint_B1953+29.pdf](https://github.com/nanograv/PINT/files/914355/tempovspint_B1953.29.pdf)
[tempovspint_J1744-1134.pdf](https://github.com/nanograv/PINT/files/914359/tempovspint_J1744-1134.pdf)
[tempovspint_J1944+0907.pdf](https://github.com/nanograv/PINT/files/914360/tempovspint_J1944.0907.pdf)
[tempovspint_J2145-0750.pdf](https://github.com/nanograv/PINT/files/914361/tempovspint_J2145-0750.pdf)

**Comment by mdecesar** [comment] 2017-04-11 19:11
Thanks Jing.  My tempo fits also did not use a solar wind model.  Wondering if anyone else has ideas about what could be causing this.

**Comment by luojing1211** [comment] 2017-04-11 19:14
If you can attach the par files, it would be a lot of help.

**Comment by mdecesar** [comment] 2017-04-11 20:33
Sure, here they are.

[B1953+29_NANOGrav_11yv0.nogls.tempopostfit.par.txt](https://github.com/nanograv/PINT/files/914588/B1953.29_NANOGrav_11yv0.nogls.tempopostfit.par.txt)
[B1953+29_NANOGrav_11yv0.tim.txt](https://github.com/nanograv/PINT/files/914589/B1953.29_NANOGrav_11yv0.tim.txt)

[J1744-1134_NANOGrav_11yv0.nogls.tempopostfit.par.txt](https://github.com/nanograv/PINT/files/914592/J1744-1134_NANOGrav_11yv0.nogls.tempopostfit.par.txt)
[J1744-1134_NANOGrav_11yv0.tim.txt](https://github.com/nanograv/PINT/files/914593/J1744-1134_NANOGrav_11yv0.tim.txt)

[J1944+0907_NANOGrav_11yv0.nogls.tempopostfit.par.txt](https://github.com/nanograv/PINT/files/914594/J1944.0907_NANOGrav_11yv0.nogls.tempopostfit.par.txt)
[J1944+0907_NANOGrav_11yv0.tim.txt](https://github.com/nanograv/PINT/files/914596/J1944.0907_NANOGrav_11yv0.tim.txt)

[J2145-0750_NANOGrav_11yv0.nogls.tempopostfit.par.txt](https://github.com/nanograv/PINT/files/914600/J2145-0750_NANOGrav_11yv0.nogls.tempopostfit.par.txt)
[J2145-0750_NANOGrav_11yv0.tim.txt](https://github.com/nanograv/PINT/files/914601/J2145-0750_NANOGrav_11yv0.tim.txt)

**Comment by luojing1211** [comment] 2017-04-13 17:04
Hi @mdecesar, 
Is the residual plot in the file showing the PINT_post_fit - PINT_pre_fit?

**Comment by luojing1211** [comment] 2017-04-14 19:24
Hi @mdecesar, Can you do the same process without T2CMETHOD TEMPO in the parfile. I don't think PINT support it currently.

**Comment by paulray** [comment] 2017-04-15 11:34
Also, maybe try setting all the DMs to 0.0 and see if the issue goes away. That would tell you if it is related to details of the dispersion calculation.

**Comment by luojing1211** [comment] 2017-04-17 21:08
Hi @mdecesar, I reproduce the PINT residual which has a difference within 2ns comparing with TEMPO2. There are several point we have to be careful about:
1. ECL : Tempo2 use IERS2003 as its value. So if you are using tempo2 make sure that agrees
2. T2CMETHOD : The one I use is IAU2000B
3. JUMP : This is the reason why we saw those frequency dependent variance. 
PINT treats JUMP as a delay and it will affect the barycentric toas. However, Tempo2 does not take jump into barycentric toas calculation. 

Now the question is how should PINT handle it?  Any comments from @paulray @scottransom @demorest ?

**Comment by mdecesar** [comment] 2017-04-17 21:32
@luojing1211 - I asked David Nice about T2CMETHOD, and he says it will not affect tempo, only tempo2.  I also ran tempo without it, just to make sure, and it does not have any effect.  However, it would affect your tempo2 runs.

So you are getting residuals that agree (within 2 ns) between PINT and tempo2, right?  I haven't tried tempo2, only tempo, but will see if I have time before the meeting.

@paulray, I'll try your DM=0 suggestion.  Do you mean to set only DM to zero, or both DM and all DMX values?

**Comment by paulray** [comment] 2017-04-18 10:36
I meant set all DMs to 0, or remove dispersion from the model entirely. Just suggesting as a test to see if the differences are frequency dependent or not.

**Comment by abhisrkckl** [comment] 2023-03-02 20:35
Can this be closed?

**Comment by scottransom** [comment] 2023-03-03 16:56
Yeah, I think so.  I'll close it.

**Closed by scottransom** 2023-03-03 16:56 UTC
