### ISSUE TITLE
Abandon Travis

### ISSUE THREAD

**Issue by matteobachetti** [nanograv/PINT#881] opened 2020-12-15 08:05 UTC
Travis has abandoned its Open Source offers
https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

We might want to use Github Actions instead, the migration is quite fast.
E.g. photutils:
https://github.com/astropy/photutils/tree/master/.github/workflows/

**Comment by paulray** [comment] 2020-12-15 14:28
Duplicate of #817

**Closed** 2020-12-15 14:32 UTC
Labels: duplicate
