### ISSUE TITLE
Could get_TOAs() be faster?

### ISSUE THREAD

**Issue by xuhengdada** [nanograv/PINT#376] opened 2018-03-07 10:38 UTC
This may costs several minutes.

Forming the TOAs from a .tim file requires lots of time. The reason for this may be using the functions in astropy.coordinates to produce the barycentric positions and velocities.

So is there any methods to make this process faster? Writing C code to achieve this? 

It takes little time in tempo2 to form BATs.

**Comment by paulray** [comment] 2018-03-07 14:30
Can you provide an example .tim file and how long it is taking to load?

**Comment by xuhenghb** [comment] 2018-03-08 05:25
oh yeah, loading the NGC6440E.tim file in the examples files of PINT costs about 241 seconds. 

I also test other .tim file, the B1855+09 NANOGrav 11yr timing data, which has 5618 toas, and this takes about 249s. 

So the number of ToAs shouldn’t be the reason.

**Comment by luojing1211** [comment] 2018-03-08 05:31
That is wried, I have never experienced this before. Can you profile the get_TOAs() method?

**Comment by scottransom** [comment] 2018-03-08 05:50
yeah...  that is some kind of strange issue with your system I would think.  Loading the NGC6440E.tim file on my machine is nearly instantaneous!  I just ran "python examples/fit_NGC6440E.py" and the fill script, including starting python, reading the TOAs, doing the fit, showing the results, and making the plots, only takes about 2 sec total.

**Comment by paulray** [comment] 2018-03-08 19:28
Yes, for me files of that size are plenty fast.
I am running into issues loading millions of TOAs when processing photon data on bright sources. This does finish as long as I run on a machine with enough memory, but it could certainly use some speedup.  One issue that could be fixed is that a TOA() object is instantiated for every single photon, then destroyed once the TOAs.table is created.  It would be better to have a shortcut to make the table directly in that case.

**Comment by xuhenghb** [comment] 2018-03-09 09:31
my machine is mac. Just now I run get_TOA() on a linux machine, same problem……sigh

Here is profile result. the result is amazing, the real time looks small, but the actual time is so long, I'm totally confused!

## Profile Result:
INFO: Applying clock corrections (include_GPS = True, include_BIPM = True. [pint.toa]
INFO: Evaluating observatory clock corrections. [pint.observatory.topo_obs]
INFO: Applying GPS to UTC clock correction (~few nanoseconds) [pint.observatory.topo_obs]
INFO: Applying TT(TAI) to TT(BIPM) clock correction (~27 us) [pint.observatory.topo_obs]
INFO: Computing TDB columns. [pint.toa]
INFO: Computing positions and velocities of observatories and Earth (planets = False), using DE421 ephemeris [pint.toa]
INFO: Adding columns ssb_obs_pos ssb_obs_vel obs_sun_pos [pint.toa]
         112172 function calls (111068 primitive calls) in 0.392 seconds
   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
… blabla ...

**Comment by paulray** [comment] 2018-03-09 15:09
Could it be the big datafile downloads?  Maybe they are not getting cached properly for some reason?
Do you see it trying to download the .bsp files?

**Comment by luojing1211** [comment] 2018-03-09 17:09
That is interesting. @paulray  I think that could be the problem, or the bandwidth is too small.  In order to avoid the download timeout problem, I added the separate line mentioned in #378

**Comment by luojing1211** [comment] 2018-03-09 17:12
@xuhenghb How long did the profiling take, not the time it reported?

**Comment by paulray** [comment] 2018-03-09 17:13
Ah, I thought that might be the reason.

**Comment by xuhenghb** [comment] 2018-03-11 13:15
Yes, Jing, no more time costing information was reported in my result. 

Now I think some downloadings may be the reason, but I don’t know what these downloadings are, may be in pint, maybe the astropy.

And another thing important is that, I have put all the datafiles needed by pint in the python directory:site-packages/ pint-0+unknown-py3.6-macosx-10.7-x86_64.egg/pint/datafiles/, 
the list of these datafiles are : 
de-403-masses.tpc
de421.bsp
de432s.bsp
earth_latest_high_prec.bpc
ecliptic.dat
finals2000A.all
gps2utc.clk
naif0012.tls
pck00010.tpc
tai2tt_bipm2015.clk
time.dat
time_ao.dat
time_bonn.dat
time_gb140.dat
time_gb853.dat
time_gbt.dat
time_jb.dat
time_nancay.dat
time_pks.dat
time_vla.dat
time_wsrt.dat

hope that no more datafiles are needed here.

**Comment by luojing1211** [comment] 2018-03-11 22:56
Maybe the DE435, DE436 as well.

**Comment by paulray** [comment] 2018-09-04 22:16
I think this has been dealt with, so I propose closing.

**Comment by aarchiba** [comment] 2019-08-28 09:32
Perhaps a test case could be added to verify this? Run get_TOAs twice and time the second one with an assertion that it didn't take too long? This should catch regressions and - if it's in the test suite - maybe notify users that their machine isn't able to correctly cache downloaded data. It may take some work to force the code to delete un-cached downloads between runs, maybe even running a script through a shell. But letting users know that caching isn't working would be valuable. Also helpful might be log messages - that the user will actually see - letting them know when files are being downloaded. (Should be INFO but those are normally suppressed. An appropriate log filter or formatter might be able to solve this.)

**Comment by aarchiba** [comment] 2019-09-09 22:28
I think we fixed the cause of this one in #502 and #508 . If it recurs, please file a new bug.

**Closed by aarchiba** 2019-09-09 22:28 UTC
