### ISSUE TITLE
unix format in pintbary

### ISSUE THREAD

**Issue by produit** [nanograv/PINT#352] opened 2017-11-02 12:13 UTC
Hi,
I try the following.
I think 150962448 is a valid unix time
produit@yoga$ pintbary 1509624488 --timescale utc --format unix --ra 12h22m33.2s --dec 19d21m44.2s --obs parkes --ephem DE405
Traceback (most recent call last):
  File "/usr/local/bin/pintbary", line 11, in <module>
    load_entry_point('pint', 'console_scripts', 'pintbary')()
  File "/home/produit/PINT/pint/scripts/pintbary.py", line 51, in main
    t = Time(args.time,scale=args.timescale,format=args.format, precision=9)
  File "/usr/local/lib/python2.7/dist-packages/astropy/time/core.py", line 253, in __init__
    precision, in_subfmt, out_subfmt)
  File "/usr/local/lib/python2.7/dist-packages/astropy/time/core.py", line 303, in _init_from_vals
    precision, in_subfmt, out_subfmt)
  File "/usr/local/lib/python2.7/dist-packages/astropy/time/core.py", line 347, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match the format class unix

**Comment by paulray** [comment] 2017-11-02 13:26
The problem is that the time argument is being passed as a string. For the 'unix' format, it seems that astropy requires that the argument be a float.  I will push a fix. Thanks!

**Comment by paulray** [comment] 2017-12-19 15:44
I believe this is resolved.  Closing.

**Closed by paulray** 2017-12-19 15:44 UTC
