### ISSUE TITLE
ELL1H issues: STIGMA crashes & lack of warnings when param is not fit

### ISSUE THREAD

**Issue by tcromartie** [nanograv/PINT#813] opened 2020-11-16 18:51 UTC
This issue came up in the context of NG 15yr notebooks. If 'STIG' is included in the parfile, STIGMA isn't fit, but no warning is given, either (the same might be true for 'VARSIGMA'). If 'STIGMA' is included in the parfile (in this case, for J1802-2124), the parfile is read, but the prefit residual plot is blank. Then, when the fit occurs, it crashes with the error "array must not contain infs or NANs." Fitting for H3/H4 works fine for this source.

**Comment by swiggumj** [comment] 2020-11-16 19:05
@tcromartie I think this may be related to a previous issue (https://github.com/nanograv/PINT/issues/801). This is partially on the PINT end (e.g. warnings), and partially on the timing_analysis end (automating the process of adding parameters when they're in the list of `fit-params`). I'll start looking into the second of those soon. If you can add any details to the issue linked above, that would be useful as I haven't had a chance to get to @dlakaplan 's question yet.

**Comment by tcromartie** [comment] 2020-11-16 19:08
I've been careful about adding the params to both the parfile and the yaml, so I don't think that's the issue. I've run into the STIGMA problem in separate contexts, too. I'll add a comment to #801.

**Comment by swiggumj** [comment] 2020-11-16 19:26
Ah I see -- didn't realize you were also making the change in the par file. I agree that shouldn't be the issue then.

**Comment by aarchiba** [comment] 2020-11-21 15:22
Can you supply a `.par`/`.tim` pair that demonstrate the problem? Presumably simplified so as not to include a hunk of the 15-year data set in github... If the problem is with the `.par` file and #814 is merged we can probably use `make_fake_toas` to demonstrate the problem without any real TOAs at all.

**Comment by aarchiba** [comment] 2020-11-25 20:27
`make_fake_toas` is now available, so if you have a `.par` file and can show us what goes wrong, I can see if I can figure out what is going wrong.

**Comment by tcromartie** [comment] 2020-11-25 21:32
Oops, sorry Anne! I just played around with this a little more, and it turns out it *works* when I don't set the starting value at 0 (i.e. the parfile reads `STIGMA  0.5  1  0.01` or something). Is that expected behavior? The fit looks bad, but it works. When the starting value is 0, I get "array must not contain infs or NaNs" (from function_base.py in asarray_chkfinite(a, dtype, order)). I've attached the par file... you don't need the tim, correct? Thank you for your help! 
[J1802-2124.basic.par.txt](https://github.com/nanograv/PINT/files/5599346/J1802-2124.basic.par.txt)

**Comment by aarchiba** [comment] 2020-11-26 22:57
Looking at Freire and Wex 2010, STIGMA=0 means sin i = 0 or a completely face-on orbit doesn't it? So maybe STIGMA=0 doesn't actually make sense? Certainly some of their equations go wrong for STIGMA=0. If that's the case then maybe we just need to ensure STIGMA != 0 in validation?

**Comment by tcromartie** [comment] 2020-12-03 15:54
Hi Anne, yeah, that's correct. I wasn't thinking. The validation it seems like you've added or proposed seems like a great idea. Thank you!

**Closed** 2020-12-03 17:02 UTC
Labels: bug
