### ISSUE TITLE
Free Travis CI is going away

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#817] opened 2020-11-18 15:57 UTC
There is a nice discussion of this on the astropy-dev list:  https://groups.google.com/g/astropy-dev/c/45frnTEAX-U

Astropy switched from Travis CI to github's "Actions" for CI.

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by JPGlaser** [comment] 2020-11-18 16:43
So we have a few options. We could use GitHub's Status API to do CI on our own hardware (depending on the strain/frequency of CI requests across nanograv's projects).
https://docs.github.com/en/free-pro-team@latest/rest/guides/building-a-ci-server

Short-term there is a possible solution to **local** runs of Travis via docker images:
https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally/49019950#49019950

**Comment by aarchiba** [comment] 2020-11-21 18:33
For local CI, `tox` was intended to be a reasonable option - runs the code with a variety of dependency versions and tests and makes doc builds. It might need a little attention to bring it back to current convenient use. 

I have a desktop machine at work I could set to running CI jobs - it's not exactly high-powered but we don't necessarily need much - but I'm not sure the IT folks would be okay with it, and I'd need their help setting up Docker and making it accessible from the Web.

**Comment by aarchiba** [comment] 2021-01-05 14:48
Closed by #882

**Closed by aarchiba** 2021-01-05 14:48 UTC
