### ISSUE TITLE
bug in photonphase

### ISSUE THREAD

**Issue by sguillot** [nanograv/PINT#408] opened 2018-08-07 21:17 UTC
I am experiencing a bug that seems to be due to some issues with astropy/numpy interaction.  It is not technically a PINT issue, but I thought others might have the same problem.

In photonphase, when no output file is provided, the event file is open in update mode.  This seems to be the cause of the crash.  My work around is to provide an output file name, but this defeats the purpose of overwrite the eventfile when adding the PULSE_PHASE column.

For example:
```
import astropy.io.fits as pyfits
hdu1 = pyfits.open('cleanfilt.evt')
print(len(hdu1[1].data))
```
works fine, but 
```
hdu1 = pyfits.open('cleanfilt.evt',mode='update')
print(len(hdu1[1].data)) 
```
crashes with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 739, in __get__
    val = self.fget(obj)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 350, in data
    data = self._get_tbdata()
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/table.py", line 171, in _get_tbdata
    self._data_offset)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 480, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 270, in readarray
    dtype=np.uint8)
  File "/home/sguillot/Softwares/anaconda3/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [Errno 22] Invalid argument
```

This happens on Ubuntu 14.04 with Python 3.6.5 (from anaconda), together with numpy 1.15.0 and astropy 2.0.7.  Note that I do not have this problem on OSX, with the same package versions!

**Comment by aarchiba** [comment] 2019-08-28 08:58
Do we have a test for this, so we can know when it's fixed? I don't see any known-fail tests, but it would be nice to close this bug when the problem is resolved.

**Comment by paulray** [comment] 2020-03-07 12:06
I've not heard of anyone else replicating this error, so I'm closing.

**Closed by paulray** 2020-03-07 12:06 UTC
Labels: upstream
