### ISSUE TITLE
Pintk: 'Home' button of plot doesn't work

### ISSUE THREAD

**Issue by juliadeneva** [nanograv/PINT#626] opened 2020-03-04 20:24 UTC
Clicking the 'Home' button above a pintk plot after zooming in doesn't go back to the original view but shows a blank plot.

**Comment by paulray** [comment] 2020-03-04 20:40
I see that behavior too.  I found that clicking 'k' does what the Home button should do.  Not sure why Home is not working, though.

**Comment by matteobachetti** [comment] 2020-12-21 09:49
Hi @paulray, @juliadeneva. This still holds, together with a worringly increasing number of bugs in pintk. Is it being abandoned, or maybe replaced by another interface?

**Comment by paulray** [comment] 2020-12-21 11:07
No, pintk is still the preferred interface. The problem is that pintk isn't tested by the integration tests, and we don't have someone whose focus is on pintk. I know @sransom was looking at some of the bugs recently. But more importantly, @champagne-cmd is starting back to work on PINT soon, so one of her tasks will be to keep pintk working and improving.

**Comment by paulray** [comment] 2020-12-21 11:08
For sure, when you find pintk bugs please file them as issues with a way to reproduce them and we'll try to get them fixed.

**Comment by scottransom** [comment] 2020-12-21 15:50
I'll try to do some work on this over the holidays.  I agree that it is terribly fragile right now.

**Comment by scottransom** [comment] 2023-07-06 15:04
This works now (at least for me).  So I think it was fixed long ago.  Closing.

**Closed by scottransom** 2023-07-06 15:04 UTC
Labels: GUI
