### ISSUE TITLE
Add a `meta` attribute to the TimingModel

### ISSUE THREAD

**Issue by JPGlaser** [nanograv/PINT#1873] opened 2024-12-12 18:40 UTC
Hey All,

Currently, `pint_pal` is pinned at version 1.0.1 because we have a few places where we store metadata about the `TimingModel` object as direct attributes. This is no longer valid in version `1.1`. As discussed on the 12/12 telecon, a quick fix would be to make a new `meta` attribute which is a dictionary. This would allow users to add metadata to the `TimingModel` without directly affecting the model itself in possibly weird ways.

See Tests found here:
https://github.com/nanograv/pint_pal/actions/runs/12300670688/job/34329402278?pr=94

~ Joe G.

**Comment by paulray** [comment] 2024-12-12 18:49
Yeah the CHANGELOG for 1.0.2 has this, which must be the cause:

- Doing model.par = something will try to assign to par.quantity or par.value but will give warning

**Comment by abhisrkckl** [comment] 2024-12-18 08:22
Added in #1874

**Closed by abhisrkckl** 2024-12-18 08:22 UTC
Labels: feature request
