### ISSUE TITLE
Tests fail but travis still passes

### ISSUE THREAD

**Issue by jellis18** [nanograv/PINT#224] opened 2017-02-17 17:00 UTC
As I was working on the BIPM clock corrections in PR #223 I noticed that many tests failed (as expected since we are changing clock corrections) but `travis` still [passes](https://travis-ci.org/nanograv/PINT).

I'm not exactly sure why this happens but perhaps a better way to do tests is to use `nosetests` or `pytest` directly with `setuptools` so that one can just use `python setup.py test` instead of the shell script used now.

I see a similar issue mentioned in Issue #195, maybe it is time to re-visit this...

**Comment by luojing1211** [comment] 2017-02-17 18:08
Hi @jellis18 , If you go to travis-ci details, a lot of ERROR and FAILs are showed in the run-test section. I think the problem is the run-test script does not report the failure as an exit 1 status.

**Comment by paulray** [comment] 2017-02-17 18:29
Strange. The shell script used to properly exit with nonzero status [when the tests failed](https://travis-ci.org/nanograv/PINT/builds/187302140).  I don't know why this would change.

However, changing travis to run nosetests directly instead of via the sh script, would be fine.

Eventually, we'd like to switch to pytest, but it seems to be in a chaotic state where no one can even agree on what the command to run tests is called.  Also, it never really worked for me.

PRs that improve the testing framework are most welcome!

**Comment by jellis18** [comment] 2017-02-18 01:55
OK,  I have a branch with some new tests but now I'm getting [this](https://travis-ci.org/jellis18/PINT/builds/202834111) problem even on the master branch.

Somehow `t.utc.iso` is giving `2006-01-15 21:24:37.834136` instead of the expected `2006-01-15 21:24:37.834078`. I get the same error on my computer and on `travis`. Although if I just run the commands from the test separately then it gives the correct result. 

Has anyone seen this before?

**Comment by luojing1211** [comment] 2017-02-18 04:06
> Somehow t.ut1.iso is giving 2006-01-15 21:24:37.834136 instead of the expected 2006-01-15 21:24:37.834078. I get the same error on my computer and on travis. Although if I just run the commands from the test separately then it gives the correct result.

Can I see your test? I need to see the way you create the time object.

**Comment by jellis18** [comment] 2017-02-18 04:23
@luojing1211, its not a new test. It is in `test_astropy_times.py`. 

```
self.lat = 19.48125
self.lon = -155.933222
earthloc = astropy.coordinates.EarthLocation.from_geodetic(self.lon,self.lat,0.0)
self.t = astropy.time.Time('2006-01-15 21:24:37.5', \
                           format='iso', scale='utc', \
                           location=earthloc, precision=6)
```

**Comment by luojing1211** [comment] 2017-02-18 04:39
@jellis18 could you show me the reference that 2006-01-15 21:24:37.834136 is the expected UT1?

**Comment by jellis18** [comment] 2017-02-18 04:59
@luojing1211, that is not the expected value but that is what I get when I run the tests. If I just copy the lines pasted above into a python interpreter then I get `2006-01-15 21:24:37.834078`. Even more strange if I go to the `tests` directory and run

`nosetests -v test_astropy_times.py`

 then I get:
```
tests.test_astropy_times.TestAstroPyTime.test_tai_tt ... ok
tests.test_astropy_times.TestAstroPyTime.test_tt_tcb ... ok
tests.test_astropy_times.TestAstroPyTime.test_tt_tcg ... ok
tests.test_astropy_times.TestAstroPyTime.test_tt_tdb ... ok
tests.test_astropy_times.TestAstroPyTime.test_ut1_tai ... ok
tests.test_astropy_times.TestAstroPyTime.test_utc ... ok
tests.test_astropy_times.TestAstroPyTime.test_utc_ut1 ... ok
tests.test_astropy_times.test_iers_a_now ... ok

----------------------------------------------------------------------
Ran 8 tests in 23.329s

OK
```
but if I run with any other tests like

`nosetests -v test_astropy_times.py test_priors.py`,

I get
```
tests.test_astropy_times.TestAstroPyTime.test_tai_tt ... ok
tests.test_astropy_times.TestAstroPyTime.test_tt_tcb ... ok
tests.test_astropy_times.TestAstroPyTime.test_tt_tcg ... ok
tests.test_astropy_times.TestAstroPyTime.test_tt_tdb ... ok
tests.test_astropy_times.TestAstroPyTime.test_ut1_tai ... ok
tests.test_astropy_times.TestAstroPyTime.test_utc ... ok
tests.test_astropy_times.TestAstroPyTime.test_utc_ut1 ... FAIL
tests.test_astropy_times.test_iers_a_now ... ok
WARNING: Unrecognized parfile line 'DMEPOCH        49453' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'EPHVER         5' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'MODE 1' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'T2CMETHOD      TEMPO' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'NE_SW          0.000' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'CHI2R          2.1896 637' [pint.models.timing_model]
WARNING: Unrecognized parfile line 'SOLARN0        00.00' [pint.models.timing_model]
test_gaussian (tests.test_priors.TestPriors) ... ok
test_gaussian_bounded (tests.test_priors.TestPriors) ... ok
test_uniform (tests.test_priors.TestPriors) ... ok
test_uniform_bounded (tests.test_priors.TestPriors) ... ok

======================================================================
FAIL: tests.test_astropy_times.TestAstroPyTime.test_utc_ut1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaellis/Envs/pint-dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jaellis/Work/Packages/PINT/tests/test_astropy_times.py", line 35, in test_utc_ut1
    assert x == y, msg
AssertionError: (2006-01-15 21:24:37.834136, 2006-01-15 21:24:37.834078)

----------------------------------------------------------------------
Ran 12 tests in 23.981s

FAILED (failures=1)
```

And this is what happens if I just run `run-tests.sh` as well. Somehow when `nosetests` uses multiple files then this happens. This makes no sense to me...

**Comment by luojing1211** [comment] 2017-02-18 05:31
I did not see it on my computer. But the test look not very good. We have to use a better way to test it.

**Comment by luojing1211** [comment] 2017-02-21 15:35
I saw the same issue on our master branch travis-ci test.

**Comment by jellis18** [comment] 2017-02-21 16:02
@luojing1211, I saw that the test failed as well. I've tried to address the testing problems in PR #225.

**Comment by luojing1211** [comment] 2017-02-22 21:30
@jellis18 
If looks like not exactly a PINT problem.  Maybe a simple astropy test code should be made only address this issue and create an issue on astropy github, if we can show that is an astropy issue.

**Comment by jellis18** [comment] 2017-02-22 21:40
@luojing1211, yes but if it is an `astropy` issue, which it must be since there are no `PINT` imports in the test then maybe we can just remove it from the tests?

**Comment by paulray** [comment] 2017-03-06 21:25
PR #225 was merged. Can we close this issue?

**Comment by jellis18** [comment] 2017-03-06 21:31
Yep

**Closed** 2017-03-06 21:38 UTC
