### ISSUE TITLE
PINT pulsar_mjd time scale out put value. 

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#366] opened 2018-02-05 17:53 UTC
Hi developers, 
Right now I have this problem of the output value for our pulsar_mjd time scale at leap second day when making the fake TOAs. The output function does not return the same value as input. My question is that should the print out value the same as the input value for our pulsar_mjd time scale.
Here is a demo to help you better understand this problem. 
```
>>> import pint.pulsar_mjd
>>> import astropy.time as ti
>>> import numpy as np
>>> import pint.utils as ut
>>> t1 = ti.Time(np.longdouble(56108.5), format='pulsar_mjd', scale='utc')
>>> t2 = ti.Time(np.longdouble(56108.5), format='mjd', scale='utc')
>>> ut.time_to_mjd_string(t2)
         '56108.500000000000000'
>>> ut.time_to_mjd_string(t1)
         '56108.499994213029942'
```

**Comment by demorest** [comment] 2018-02-05 18:18
Hi Jing, the problem is in the `pint.utils.time_to_mjd_string()` function.  It directly accesses the `jd1` and `jd2` values within the `Time` object, this effectively converts a pulsar_mjd time back to a normal astropy mjd time, leading to the discrepancy you see.  I can put in a fix for this, will just take a sec.

**Comment by demorest** [comment] 2018-02-05 19:13
See PR #367

**Closed** 2018-02-13 19:06 UTC
